sudo: false
language: node_js
node_js:
  # dropping support for node 0.10 - "0.10"
  # - "0.12"
  # - "4"
  # - "5"
  - "6"
  - "7"



before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
  # memcpy only works with node version > 0.8 and <= 0.12, and not with io.js, at this time
  - if [[ `node --version` == v0.12 ]]; then npm i memcpy ; fi
  - npm install
  - if [[ `node --version` == v0.10* ]]; then npm i ursa@0.8.5 ; fi

after_success:
  - make test-cov
script:
  - npm test 

addons:
  code_climate:
    repo_token: 0860a573fd01a1fbafc298b7c40cd0c1fd8b25e5f53a5e8346d3b42cb40ab48e



notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d51130aaea652dbc8f1
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
