language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov
