language: node_js
node_js:
  - "0.10"
  - "0.11"

before_script:
  - npm install -g istanbul coveralls
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
  - npm install

after_success:
  - make coveralls
script:
  - npm test
  - make test-cov

addons:
  code_climate:
    repo_token: 0860a573fd01a1fbafc298b7c40cd0c1fd8b25e5f53a5e8346d3b42cb40ab48e

after_script:
  - cat coverage/lcov.info | codeclimate


webhooks:
  urls:
    - https://webhooks.gitter.im/e/8a4a66d8a690192fcb3f
    - https://webhooks.gitter.im/e/e8977b99e89bdf6d8763
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
