# Test against this version of Node.js
environment:
  matrix:
  # - nodejs_version: "4" (not supported any more)
  # - nodejs_version: "6" (not supported anu more => lack of util.promisify )
  - nodejs_version: "8"
  - nodejs_version: "9"
  - nodejs_version: "10"
platform:
  - x64
  - x86

matrix:
  allow_failures:
    - nodejs_version: "0.10"

# fix lineendings in Windows
init:
    - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    - git config --global core.autocrlf input


# Install scripts. (runs after repo cloning)
install:
  - npm install npm -g
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules (using appveyor-retry to prevent EPERM bug)
  - appveyor-retry npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
