# Test against this version of Node.js
environment:
  matrix:
    # - nodejs_version: "4" (not supported any more)
    # - nodejs_version: "6" (not supported anu more => lack of util.promisify )
    # - nodejs_version: "8" ( Jan 2021 -> not supported any more sicnce Jan 2020 - lack for await require by new version of mocha)
    # - nodejs_version: "9"  (not supported any more)
    # - nodejs_version: "10" (not supported any mopre -> end of life 2021-04-30)
    # - nodejs_version: "11" (not supported any more)
    - nodejs_version: "12" 
    - nodejs_version: "14"
    - nodejs_version: "15"

platform:
  - x64
  - x86

matrix:
  allow_failures:
    - nodejs_version: "0.10"

# fix lineendings in Windows
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - git config --global core.autocrlf input

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules (using appveyor-retry to prevent EPERM bug)
  - npm install -g npm pnpm typescript ts-node
  - set path=C:\Users\appveyor\AppData\Roaming\npm\;%path%
  - tsc --version
  - appveyor-retry pnpm recursive install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - pnpm --version
  # run tests
  - pnpm run pretest
  - pnpm test
  # run typescript in packages that have some
  # - node  ./node_modules/lerna/cli.js run test-typescript

# Don't actually build.
build: false

cache:
  - node_modules                        # local npm modules
  - '%APPDATA%\npm-cache'               # npm cache
